name: pinact

on:
  pull_request:

permissions:
  contents: read

jobs:
  pinact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: suzuki-shunsuke/pinact-action@1dbe7e5a71dff1e8e6e478bff62dafa9cd13f45d # v1.1.0
        with:
          verify: true
