name: Supply Chain

on:
  pull_request:

permissions:
  contents: read

jobs:
  npm-supply-chain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: npm ci
      - run: npm run check:supply-chain
      - run: npm run audit
      - run: npm run audit:signatures
      - run: npm run --silent sbom > sbom.cyclonedx.json
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: sbom-cyclonedx
          path: sbom.cyclonedx.json
          if-no-files-found: error
