name: Supply Chain

on:
  pull_request:

permissions:
  contents: read

jobs:
  npm-supply-chain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: npm ci
      - run: npm run check:supply-chain
      - run: npm run audit
      - run: npm run audit:signatures
      - run: npm run --silent sbom > sbom.cyclonedx.json
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: sbom-cyclonedx
          path: sbom.cyclonedx.json
          if-no-files-found: error
